# Generated by Django 4.0.4 on 2022-05-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
