# Generated by Django 4.0.4 on 2022-05-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='department',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
