# Generated by Django 4.0.4 on 2022-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_students_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['stuId']},
        ),
        migrations.AddField(
            model_name='students',
            name='stuId',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
