# Generated by Django 4.0.4 on 2022-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_students_options_students_stuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
