# Generated by Django 4.0.4 on 2022-05-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['status', 'level', 'department', 'stuId']},
        ),
    ]
