# Generated by Django 4.0.4 on 2022-05-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_student_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['stuId', 'status']},
        ),
    ]
