# Generated by Django 4.0.4 on 2022-05-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['status', 'stuId']},
        ),
    ]
