# Generated by Django 4.0.4 on 2022-05-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['status', '-stuId']},
        ),
    ]
