# Generated by Django 4.0.4 on 2022-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('First Level', 'First Level'), ('Second Level', 'Second Level'), ('Third Level', 'Third Level'), ('Fourth Level', 'Fourth Level')], max_length=50),
        ),
    ]
