# Generated by Django 4.0.4 on 2022-05-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_student_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['status', 'stuId']},
        ),
    ]
